name: PR_template

on:
  pull_request:
    branches: [main,develop]
    type: [closed]
jobs:
  build1:
    name: Build(1)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: hi
        run: |
         echo "${{secrets.ENV}}"
         echo "????"
         echo "merge"
         python -m test
  build2:
    need: build(1)
    name: Build(2)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: hi
        run: |
         echo "${{secrets.ENV}}"
         echo "pr.merge"
         echo "merge2"
         python -m test
        