name: PR_template

on:
  pull_request:
    branches: [main,develop]
jobs:
  build1:
    name: Build1
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - name: hi
        run: |
         echo "${{secrets.ENV}}"
         echo "pr"
         echo "merge2"
         python -m test
  build2:
    name: Build2
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: hi
        run: |
         echo "${{secrets.ENV}}"
         echo "pr.merge"
         echo "merge2"
         python -m test
        